library(haven)
library(admiral)
library(dplyr)
library(tidyr)
library(metacore)
library(metatools)
library(xportr)

ae <- read_xpt("sdtm/ae.xpt")
cm <- read_xpt("sdtm/cm.xpt")
dm <- read_xpt("sdtm/dm.xpt")
ds <- read_xpt("sdtm/ds.xpt")
ex <- read_xpt("sdtm/ex.xpt")
lb <- read_xpt("sdtm/lb.xpt")
mh <- read_xpt("sdtm/mh.xpt")
qs <- read_xpt("sdtm/qs.xpt")
sc <- read_xpt("sdtm/sc.xpt")
se <- read_xpt("sdtm/se.xpt")
sv <- read_xpt("sdtm/sv.xpt")
ta <- read_xpt("sdtm/ta.xpt")
te <- read_xpt("sdtm/te.xpt")
ti <- read_xpt("sdtm/ti.xpt")
ts <- read_xpt("sdtm/ts.xpt")
tv <- read_xpt("sdtm/tv.xpt")
vs <- read_xpt("sdtm/vs.xpt")
relrec <- read_xpt("sdtm/relrec.xpt")
suppae <- read_xpt("sdtm/suppae.xpt")
suppdm <- read_xpt("sdtm/suppdm.xpt")
suppds <- read_xpt("sdtm/suppds.xpt")
supplb <- read_xpt("sdtm/supplb.xpt")

xportr_write(adsl, "adam/adsl.xpt")
